production:
  adapter: postgresql
  encoding: unicode
  database: lenses_prod
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: lenses_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: lenses_test
  pool: 5
  timeout: 5000

